apiVersion: v1
kind: Secret
metadata:
  name: xmoto-web-api-secrets
  namespace: staging
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
stringData:
  EXAMPLE_SECRET: ENC[AES256_GCM,data:JazptCGsMQ==,iv:1tEcppufgal4+KHhOZGURSXJp3JgXa7O1eBu94RptCA=,tag:X51dJ6Olg6ZU22NsFoEczw==,type:str]
sops:
  age:
    - recipient: age1de22saduxts5n3vzzqhk2kpfta64aq5cqj0kuycen4j8eqvhpqaqapezq7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTFSNmFCc3pBWGduVkMz
        L0VTQ1cyQVRrN20raDhkTHp5ek9BVmlLOXpjCnZMQjdMdndkZ1pRUW5JRjhJRndU
        b0ZmNW9vOSt1cm1VUkNHeUJQbXZKOTAKLS0tIFRvMDRRN2VoS2FQVzhPR3VCOWIw
        L1ZHaXdPT1I2TFR3cis3OExhbjRzWncKXa2WZ0DiyZbiqBPDOqZHTYlNf8Jre1Yr
        pwRQVH90jZkP4b4tHihpNPZrbTB+co6YnDYTnYoWQRl5ZjdwOz5pFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T20:49:13Z"
  mac: ENC[AES256_GCM,data:U/qOxIQFzKY3788H9m24VqpeZ3L+U2iXXq+1Ux82fdntIKC0mWXCJDaC63INK5C6Y0ng5UNFpVZF0sCgYLnVkd5McqVRvaqVywvIYPodd3uHJLt+eFuQGmWi3uk7y4mp5tl67xsXVyi3x+bva4bcYEVEeEVDKMX8HnwR7Nup4DQ=,iv:cK5JknaCpdsR7OIh8N+x4UwC+mA/ZqGOQzhl3uKgOFE=,tag:2CzoacuqMitgQkEiEqXG+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
