apiVersion: v1
kind: Secret
metadata:
  name: xmoto-web-site-secrets
  namespace: prod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
stringData:
  EXAMPLE_SECRET: ENC[AES256_GCM,data:LNZsmrAgsg==,iv:/Cwl5RMrJkSe2lDO1SeYP7Rsp3yjkhd156h1Edos1as=,tag:IJGuYZvELPQEeCwdqOLifw==,type:str]
sops:
  age:
    - recipient: age1de22saduxts5n3vzzqhk2kpfta64aq5cqj0kuycen4j8eqvhpqaqapezq7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdmQ4c2sxaGxJclplTnRW
        ZGFLQjRmRzVzUDBZRGdhdzdLVEdkbDk0VjJVCkdsb0dVWk9JdXNwSjJhak8zcUtl
        ejY4RW1zVjI5MFU0bGNwSFhlQVhqYjQKLS0tIE5DaXhHKzFvd0xnS1VMK1VQQ3lz
        UWFBbEdEc2R3VGJjL0VYb2luT0lZSEUKhBtCGW5YyGZmbZPHFJpJBMzSMiivO8/V
        IV9nFs9tLL86J8P5JdEM/nsTfpdkC2MCrfBrSwsVumlle38VNRhNoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T10:46:56Z"
  mac: ENC[AES256_GCM,data:9P5D6HBRajBIQ0JA3BW1o4SGkx/jgHCbTQfAm38Bd36XeZwkOmHljHTg0LEI1c2NC8Au5+SmISA081N0w6PC/emBTKNbRWJGO6xucSRwn1Wb9lDrH6dGDITwaEaoJqaJ8MSGdKeWdr+Z9iNYv60BgrC7vnyHzzEqRD3W84Srvto=,iv:RbpGWjbQIQsARMJjnTkdYcPqI3Wf/XNHXFcbaNqjk/g=,tag:kGv9TUTiWZwlV0OCQhvOVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
