apiVersion: v1
kind: Secret
metadata:
  name: xmoto-web-api-secrets
  namespace: prod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
stringData:
  EXAMPLE_SECRET: ENC[AES256_GCM,data:LNZsmrAgsg==,iv:/Cwl5RMrJkSe2lDO1SeYP7Rsp3yjkhd156h1Edos1as=,tag:IJGuYZvELPQEeCwdqOLifw==,type:str]
sops:
  age:
    - recipient: age1de22saduxts5n3vzzqhk2kpfta64aq5cqj0kuycen4j8eqvhpqaqapezq7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdmQ4c2sxaGxJclplTnRW
        ZGFLQjRmRzVzUDBZRGdhdzdLVEdkbDk0VjJVCkdsb0dVWk9JdXNwSjJhak8zcUtl
        ejY4RW1zVjI5MFU0bGNwSFhlQVhqYjQKLS0tIE5DaXhHKzFvd0xnS1VMK1VQQ3lz
        UWFBbEdEc2R3VGJjL0VYb2luT0lZSEUKhBtCGW5YyGZmbZPHFJpJBMzSMiivO8/V
        IV9nFs9tLL86J8P5JdEM/nsTfpdkC2MCrfBrSwsVumlle38VNRhNoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T20:49:09Z"
  mac: ENC[AES256_GCM,data:bhh2MprEO4TdFZun3vdyVUGUxojvs4+TxZlgz2l+UiXGjuPPM4y42+tpWqbm814kmuSNUeRxSDu2NnsvP23gfEmFBITeQaxdi0Iz2UfuNPZhX00+O4u9d3cc7qrsF4h3TMspS4lXpZGxdgVDC54nMciF0d+l6ddu7wQxsY/s19M=,iv:Fv8aJqweadHhw6/29kpz7/3zLgg4Mcfdx2vbqCRvkxo=,tag:EFmYSs99prclgseu8LJ80g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
